// index_codebase.js
// A simple Node script to generate a JSON and markdown index of TypeScript/TSX files
// It scans the repo for .ts, .tsx, .js, .jsx files, extracts exported symbol names
// and writes code-index.json and CODE_INDEX.md in the project root.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

function walk(dir) {
    const files = fs.readdirSync(dir, { withFileTypes: true });
    let results = [];
    for (const file of files) {
        if (file.name === 'node_modules' || file.name === '.git' || file.name === 'dist' || file.name === 'build') continue;
        const res = path.resolve(dir, file.name);
        if (file.isDirectory()) results = results.concat(walk(res));
        else results.push(res);
    }
    return results;
}

function findExports(content) {
    const exports = new Set();
    const exportRegex = /export\s+(default\s+)?(class|function|const|let|var|interface|type|enum)?\s*([A-Za-z0-9_]+)/g;
    let match;
    while ((match = exportRegex.exec(content)) !== null) {
        const name = match[3] || 'default';
        exports.add(name);
    }
    // Also catch "export { A, B } from './x'" pattern
    const namedExportsRegex = /export\s*\{([^}]+)\}/g;
    while ((match = namedExportsRegex.exec(content)) !== null) {
        const inside = match[1];
        inside.split(',').map(s => s.trim().split(' as ')[0].trim()).forEach(p => p && exports.add(p));
    }
    return Array.from(exports);
}

function typeForFile(filePath) {
    if (filePath.includes(`${path.sep}components${path.sep}`)) return 'component';
    if (filePath.includes(`${path.sep}services${path.sep}`)) return 'service';
    if (filePath.includes(`${path.sep}contracts${path.sep}`)) return 'contract';
    const ext = path.extname(filePath);
    if (ext === '.json') return 'config';
    if (filePath.endsWith('index.tsx') || filePath.endsWith('App.tsx')) return 'entry';
    return 'utility';
}

function relative(p) {
    return path.relative(ROOT_DIR, p).split('\\').join('/');
}

const allFiles = walk(ROOT_DIR).filter(f => ['.ts','.tsx','.js','.jsx','.json','.move'].includes(path.extname(f)));
const index = [];

for (const file of allFiles) {
    const content = fs.readFileSync(file, 'utf8');
    const exports = findExports(content);
    index.push({ path: relative(file), type: typeForFile(file), exports, size: content.length });
}

// Write JSON Index
fs.writeFileSync(path.join(ROOT_DIR,'code-index.json'), JSON.stringify(index, null, 2));

// Write Markdown
let md = `# Project Code Index\n\nGenerated by scripts/index_codebase.js\n\n`;
md += `Total files indexed: ${index.length}\n\n`;
const grouped = index.reduce((acc, item) => { acc[item.type] = acc[item.type] || []; acc[item.type].push(item); return acc; }, {});

for (const [group, files] of Object.entries(grouped)) {
    md += `## ${group.charAt(0).toUpperCase() + group.slice(1)}\n\n`;
    files.sort((a,b) => a.path.localeCompare(b.path));
    for (const f of files) {
        const exportsList = f.exports.length ? f.exports.join(', ') : '*no exports*';
        md += '- `' + f.path + '` — Exports: ' + exportsList + '\n';
    }
    md += '\n';
}

md += `---\n\n## How to regenerate\n\n- Node.js required. Run:\n\n\n`;
md += '``\nnode scripts/index_codebase.js\n``\n\n';
md += 'This will update `code-index.json` and `CODE_INDEX.md`.\n';

fs.writeFileSync(path.join(ROOT_DIR,'CODE_INDEX.md'), md);
console.log('Index generated: code-index.json and CODE_INDEX.md');
